"use client";

import { useEffect, useState} from "react";

export function ProjectsSection() {
  const [isVisible, setIsVisible] = useState(false);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.2 }
    );

    const element = document.getElementById("projects");
    if (element) observer.observe(element);

    return () => observer.disconnect();
  }, []);

  return (
    <section id="projects" className="relative py-20 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="relative">
          <h2 className="text-4xl md:text-5xl font-bold font-inter text-center mb-16">
            <span className="bg-gradient-to-r from-aurora-lavender to-aurora-green bg-clip-text text-transparent">
              Featured Projects
            </span>
          </h2>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {experiences.map((exp, index) => (
              <div
                key={exp.id}
                className="relative transition-all duration-1000"
              >
                <div className="relative bg-cosmic-blue/50 backdrop-blur-sm border border-aurora-cyan/20 rounded-2xl p-6">
                  <div className="relative">
                    <h3 className="text-xl font-bold text-aurora-cyan mb-4">
                      {exp.title}
                    </h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
            </div>
          </div>
        </div>
      </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div>
        </div>
            </div>
          </div}
        </div>
            </div>
          </div}
        </div>
            </div>
          </div}
        </div>
            </div>
          </div}
        </div>
            </div>
          </div}
        </div>
            </div>
          </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div>
            </div}
        </div}
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div>
        </div}
        </div>
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
        </div}
